apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-{{ .Values.app.name }}
  namespace: deployment-{{ .Values.app.env }}
  labels:
    app: {{ .Values.app.name }}
    env: {{ .Values.app.env }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
      env: {{ .Values.app.env }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        env: {{ .Values.app.env }}
    spec:
      restartPolicy: Always
      containers:
      - name: container-{{ .Values.app.name }}
        image: {{ .Values.app.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "512m"
          limits:
            memory: "512Mi"
            cpu: "1024m"


