apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-{{ .Values.app.name }}
  namespace: deployment-{{ .Values.app.env }}
  labels:
{{ include "handson.labels" . | indent 4 }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
      env: {{ .Values.app.env }}
  template:
    metadata:
      labels:
{{ include "handson.labels" . | indent 8 }}
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      automountServiceAccountToken: false
      runtimeClassName: gvisor
      restartPolicy: Always
      containers:
      - name: container-{{ .Values.app.name }}
        image: {{ .Values.app.image }}
        imagePullPolicy: Always
        securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readonlyRootFilesystem: true
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "512m"
          limits:
            memory: "512Mi"
            cpu: "1024m"


