apiVersion: v1
kind: Service
metadata:
  name: service-{{ .Values.app.name }}
  namespace: deployment-{{ .Values.app.env }}
spec:
  selector:
    app: {{ .Values.app.name }}
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080