apiVersion: v1
kind: Secret
metadata:
  name: secret-credentials
  namespace: jenkins
type: Opaque
data:
{{- range $v := .Values.jenkins_credentials }}
  {{ $v.name }}: {{ $v.value | toString | b64enc }}
{{- end }}